model:
  name: "Momask_RVQVAE"
  batch_size: 256
  checkpoints_dir: ./evaluation/models
  code_dim: 512
  commit: 0.02
  dataset_name: t2m
  depth: 3
  dilation_growth_rate: 3
  down_t: 2
  eval_every_e: 1
  feat_bias: 5
  gamma: 0.05
  gpu_id: 0
  is_continue: False
  is_train: True
  log_every: 10
  loss_vel: 0.5
  lr: 0.0002
  lr_scheduler: [150000, 250000]
  max_epoch: 50
  mu: 0.99
  nb_code: 512
  num_quantizers: 6
  output_emb_width: 512
  quantize_dropout_prob: 0.2
  recons_loss: l1_smooth
  save_every_e: 2
  save_latest: 500
  shared_codebook: False
  stride_t: 2
  vq_act: relu
  vq_norm: None
  warm_up_iter: 2000
  weight_decay: 0.0
  width: 512
  window_size: 64
train:
  full_motion: true