batch_size: 32
checkpoints_dir: ./checkpoints
cond_scale: 2.0
dataset_name: kit
dropout: 0.2
ext: text2motion
ff_size: 1024
force_mask: false
gpu_id: -1
gumbel_sample: false
latent_dim: 384
mask_edit_section: null
max_motion_length: 196
motion_length: 0
n_heads: 6
n_layers: 8
name: t2m_nlayer8_nhead6_ld384_ff1024_cdp0.1_rvq6ns_k
num_batch: 2
repeat_times: 1
res_name: tres_nlayer8_ld384_ff1024_rvq6ns_cdp0.2_sw_k 
seed: 10107
source_motion: example_data/000612.npy
temperature: 1.0
text_path: ''
text_prompt: ''
time_steps: 10
topkr: 0.9
unit_length: 4
use_res_model: true
vq_name: rvq_nq1_dc512_nc512
which_epoch: latest
